[package]
name = "homoglyphs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.17" }
domain = { path = "../domain" }
drivers = { path = "../drivers" }
service = { path = "../service" }
tabled = "0.8.0"
