[package]
name = "drivers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tantivy = { version = "0.18.0" } #, default-features = false
domain = { path = "../domain" }
dirs = "4.0.0"
